[world]
name = "StarkFantasy"
description = "StarkFantasy League on Starknet is a Web3 game where players join pools, assemble virtual teams, and compete for rewards in a decentralized and transparent system."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/dojoengine/dojo-starter"
seed = "starkfantasy"

[world.socials]
x = "https://x.com/ohayo_dojo"

[namespace]
default = "starkfantasy"

[env]
rpc_url = "https://api.cartridge.gg/x/starkfantasy/katana"
account_address = "0x6677fe62ee39c7b07401f754138502bab7fac99d2d3c5d37df7d1c6fab10819"
private_key = "0x3e3979c1ed728490308054fe357a9f49cf67f80f9721f44cc57235129e090f4"
# world_address = "0x032a12dd0743319be2bc788e61cebe8aa8d8b9775cedf8af81425f47a9b4fcb5"

[writers]
"starkfantasy" = ["starkfantasy-bet", "starkfantasy-user"]
