[world]
name = "StarkFantasy"
description = "StarkFantasy League on Starknet is a Web3 game where players join pools, assemble virtual teams, and compete for rewards in a decentralized and transparent system."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/dojoengine/dojo-starter"
seed = "starkfantasy"

[world.socials]
x = "https://x.com/ohayo_dojo"

[namespace]
default = "starkfantasy"

[env]
rpc_url = "http://katana:5050/"
# Default account for katana with seed = 0
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
# world_address = "0x06171ed98331e849d6084bf2b3e3186a7ddf35574dd68cab4691053ee8ab69d7"

[writers]
"starkfantasy" = ["starkfantasy-bet", "starkfantasy-user"]
